<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DeliveryApiController as Api;
Route::get('/health',[Api::class,'health']);
Route::post('/auth/login',[Api::class,'login']); Route::post('/auth/refresh',[Api::class,'refresh']); Route::post('/auth/logout',[Api::class,'logout']); Route::post('/auth/change-password',[Api::class,'changePassword']); Route::post('/auth/forgot-password',[Api::class,'forgotPassword']); Route::post('/auth/reset-password',[Api::class,'resetPassword']);
Route::get('/users/me',[Api::class,'me']); Route::get('/users',[Api::class,'users']); Route::post('/users',[Api::class,'createUser']); Route::put('/users/{id}',[Api::class,'updateUser']); Route::delete('/users/{id}',[Api::class,'deleteUser']); Route::get('/admin/users',[Api::class,'users']); Route::patch('/admin/users/{id}',[Api::class,'updateUser']); Route::patch('/admin/users/{id}/password',[Api::class,'updateUserPassword']); Route::put('/users/{id}/role',[Api::class,'updateUser']);
Route::get('/admin/summary',[Api::class,'adminSummary']); Route::get('/admin/overview',[Api::class,'adminOverview']); Route::get('/admin/roles',[Api::class,'roles']); Route::get('/admin/logs',[Api::class,'adminLogs']); Route::get('/settings/system',[Api::class,'settings']); Route::put('/settings/system',[Api::class,'updateSettings']);
Route::get('/roles',[Api::class,'roles']); Route::get('/logs',[Api::class,'adminLogs']);
Route::get('/drivers',[Api::class,'drivers']); Route::get('/people/search',[Api::class,'searchPeople']); Route::get('/search/people',[Api::class,'searchPeople']); Route::get('/search/drivers',[Api::class,'searchDrivers']); Route::get('/recipients/suggestions',[Api::class,'recipients']); Route::get('/recipients/phone',[Api::class,'recipientPhone']); Route::get('/customers/recipients',[Api::class,'recipients']); Route::post('/drivers/visibility',[Api::class,'driverVisibility']);
Route::get('/products',[Api::class,'products']); Route::get('/articles/products',[Api::class,'products']);
Route::get('/customers/suggest/{field}',[Api::class,'suggest'])->whereIn('field',['names','emails','phones']);
Route::get('/work-orders/suggestions',[Api::class,'workOrderSuggestions']); Route::post('/external/work-orders',[Api::class,'externalWorkOrders']);
Route::get('/orders',[Api::class,'orders']); Route::get('/deliveries',[Api::class,'orders']); Route::post('/orders',[Api::class,'createOrder']); Route::post('/deliveries',[Api::class,'createOrder']); Route::put('/orders/{id}',[Api::class,'updateOrder']); Route::patch('/deliveries/{id}',[Api::class,'updateOrder']);
Route::post('/orders/{id}/start',[Api::class,'startOrder']); Route::post('/deliveries/{id}/start',[Api::class,'startOrder']); Route::post('/orders/{id}/stop',[Api::class,'stopOrder']); Route::post('/deliveries/{id}/stop',[Api::class,'stopOrder']); Route::patch('/orders/{id}/delivered',[Api::class,'delivered']); Route::post('/deliveries/{id}/delivered',[Api::class,'delivered']); Route::post('/orders/{id}/location',[Api::class,'location']); Route::post('/deliveries/{id}/location',[Api::class,'location']); Route::post('/orders/{id}/resend-tracking-sms',[Api::class,'resendSms']); Route::post('/deliveries/{id}/resend-tracking-sms',[Api::class,'resendSms']); Route::delete('/orders/{id}',[Api::class,'deleteOrder']); Route::delete('/orders',[Api::class,'clearOrders']);
Route::get('/track/{token}',[Api::class,'track']); Route::get('/track/{token}/stream',[Api::class,'trackStream']);
Route::get('/notifications/config',[Api::class,'notificationConfig']); Route::get('/push/config',[Api::class,'notificationConfig']); Route::post('/push/subscribe',[Api::class,'pushSubscribe']); Route::post('/notifications/subscription',[Api::class,'pushSubscribe']); Route::delete('/notifications/subscription',[Api::class,'pushDelete']); Route::get('/notifications/subscriptions/me',[Api::class,'mySubscriptions']); Route::post('/push/test',[Api::class,'pushTest']); Route::post('/notifications/test-me',[Api::class,'pushTest']); Route::get('/admin/notifications/subscriptions',[Api::class,'allSubscriptions']); Route::post('/admin/notifications/test-user/{id}',[Api::class,'pushTest']); Route::post('/admin/notifications/broadcast-test',[Api::class,'pushTest']);
